version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - cg_network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: "laravel-cg"
      DB_USERNAME: "root"
      DB_PASSWORD: "StrongRootPassword"
    volumes:
      - ./backend:/var/www/html/backend

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "laravel-cg"
      MYSQL_ROOT_PASSWORD: "StrongRootPassword"
    volumes:
      - ./backend/mysql_data:/var/lib/mysql
    networks:
      - cg_network

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    container_name: vue
    restart: always
    networks:
      - cg_network

networks:
  cg_network:

volumes:
  mysql_data:
  backend:
